#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <algorithm>
#include <iomanip>
#include <dirent.h>
#include <sys/stat.h>

bool ends_with(const std::string& str, const std::string& suffix) {
    return str.size() >= suffix.size() && 
           str.compare(str.size() - suffix.size(), suffix.size(), suffix) == 0;
}

std::string replace_all(std::string str, const std::string& from, const std::string& to) {
    size_t start_pos = 0;
    while((start_pos = str.find(from, start_pos)) != std::string::npos) {
        str.replace(start_pos, from.length(), to);
        start_pos += to.length();
    }
    return str;
}

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cerr << "Usage: " << argv[0] << " <input_dir> <output_cpp>" << std::endl;
        return 1;
    }

    std::string input_dir = argv[1];
    std::string output_cpp = argv[2];

    DIR* dir = opendir(input_dir.c_str());
    if (!dir) {
        std::cerr << "Error: Could not open directory " << input_dir << std::endl;
        return 1;
    }

    std::vector<std::string> rbx_files;
    struct dirent* entry;
    while ((entry = readdir(dir)) != nullptr) {
        std::string filename = entry->d_name;
        if (ends_with(filename, ".rbx")) {
            rbx_files.push_back(filename);
        }
    }
    closedir(dir);

    std::sort(rbx_files.begin(), rbx_files.end());

    std::ofstream out(output_cpp);
    if (!out.is_open()) {
        std::cerr << "Error: Could not open output file " << output_cpp << std::endl;
        return 1;
    }

    out << "// Automatically generated by bin2c. Do not edit.\n";
    out << "#include \"../include/rit/vfs.hpp\"\n\n";

    for (const auto& filename : rbx_files) {
        std::string filepath = input_dir + "/" + filename;
        std::string var_name = replace_all(filename, ".", "_");

        std::ifstream in(filepath, std::ios::binary);
        if (!in.is_open()) {
            std::cerr << "Error: Could not open input file " << filepath << std::endl;
            return 1;
        }

        std::vector<unsigned char> data((std::istreambuf_iterator<char>(in)),
                                         std::istreambuf_iterator<char>());
        in.close();

        out << "static const unsigned char " << var_name << "_data[] = {\n";
        for (size_t i = 0; i < data.size(); ++i) {
            if (i % 12 == 0) {
                out << "    ";
            }
            out << "0x" << std::hex << std::uppercase << std::setfill('0') << std::setw(2) << (int)data[i];
            if (i + 1 < data.size()) {
                out << ", ";
            } else {
                out << ",";
            }
            if ((i + 1) % 12 == 0 || i + 1 == data.size()) {
                out << "\n";
            }
        }
        out << "};\n";
        out << "static const unsigned int " << var_name << "_len = " << std::dec << data.size() << ";\n\n";
    }

    out << "extern \"C\" void ritos_load_embedded_apps() {\n";
    for (const auto& filename : rbx_files) {
        std::string var_name = replace_all(filename, ".", "_");
        out << "    rit::VFS::create_file(\"/sys/" << filename << "\", (const char*)" << var_name << "_data, " << var_name << "_len);\n";
    }
    out << "}\n";

    out.close();
    std::cout << "Generated " << output_cpp << " containing " << rbx_files.size() << " apps." << std::endl;
    return 0;
}
