#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <algorithm>
#include <iomanip>

std::string replace_all(std::string str, const std::string& from, const std::string& to) {
    size_t start_pos = 0;
    while((start_pos = str.find(from, start_pos)) != std::string::npos) {
        str.replace(start_pos, from.length(), to);
        start_pos += to.length();
    }
    return str;
}

int main(int argc, char* argv[]) {
    if (argc < 3) {
        std::cerr << "Usage: " << argv[0] << " <output_cpp> <vfs-path>=<file>..." << std::endl;
        return 1;
    }

    std::string output_cpp = argv[1];

    // (vfs destination path, source file path) pairs
    std::vector<std::pair<std::string, std::string>> rbx_files;
    for (int i = 2; i < argc; ++i) {
        std::string arg = argv[i];
        size_t eq = arg.find('=');
        if (eq == std::string::npos || eq == 0 || eq + 1 >= arg.size()) {
            std::cerr << "Error: expected <vfs-path>=<file>, got '" << arg << "'" << std::endl;
            return 1;
        }
        rbx_files.push_back({arg.substr(0, eq), arg.substr(eq + 1)});
    }

    std::sort(rbx_files.begin(), rbx_files.end());

    // Two files embedding under the same VFS path would silently shadow each
    // other - refuse instead.
    for (size_t i = 1; i < rbx_files.size(); ++i) {
        if (rbx_files[i].first == rbx_files[i-1].first) {
            std::cerr << "Error: duplicate VFS path '" << rbx_files[i].first << "' ("
                      << rbx_files[i-1].second << " vs " << rbx_files[i].second << ")" << std::endl;
            return 1;
        }
    }

    std::ofstream out(output_cpp);
    if (!out.is_open()) {
        std::cerr << "Error: Could not open output file " << output_cpp << std::endl;
        return 1;
    }

    out << "// Automatically generated by bin2c. Do not edit.\n";
    out << "#include <rit/virtual_filesystem.hpp>\n\n";

    for (const auto& [vfs_path, filepath] : rbx_files) {
        std::string var_name = replace_all(replace_all(vfs_path, ".", "_"), "/", "_");

        std::ifstream in(filepath, std::ios::binary);
        if (!in.is_open()) {
            std::cerr << "Error: Could not open input file " << filepath << std::endl;
            return 1;
        }

        std::vector<unsigned char> data((std::istreambuf_iterator<char>(in)),
                                         std::istreambuf_iterator<char>());
        in.close();

        out << "static const unsigned char " << var_name << "_data[] = {\n";
        for (size_t i = 0; i < data.size(); ++i) {
            if (i % 12 == 0) {
                out << "    ";
            }
            out << "0x" << std::hex << std::uppercase << std::setfill('0') << std::setw(2) << (int)data[i];
            if (i + 1 < data.size()) {
                out << ", ";
            } else {
                out << ",";
            }
            if ((i + 1) % 12 == 0 || i + 1 == data.size()) {
                out << "\n";
            }
        }
        out << "};\n";
        out << "static const unsigned int " << var_name << "_len = " << std::dec << data.size() << ";\n\n";
    }

    out << "extern \"C\" void ritos_load_embedded_apps() {\n";
    for (const auto& [vfs_path, filepath] : rbx_files) {
        std::string var_name = replace_all(replace_all(vfs_path, ".", "_"), "/", "_");
        out << "    rit::VFS::create_file(\"" << vfs_path << "\", (const char*)" << var_name << "_data, " << var_name << "_len);\n";
    }
    out << "}\n";

    out.close();
    std::cout << "Generated " << output_cpp << " containing " << rbx_files.size() << " apps." << std::endl;
    return 0;
}
