#!/usr/bin/env python3
"""Bakes the Instrument Sans system font into an alpha-coverage atlas header.

Each face is rasterized with FreeType (via Pillow) at build time into 8-bit
antialiased coverage bitmaps, so the kernel renders smooth proportional text
with a trivial per-pixel blend and no runtime TTF parsing.

Digits are forced onto a shared (tabular) advance per face so clocks and
counters don't wobble as the digits change.
"""
import os, sys

FONT_DIR = "assets/sources/fonts/Instrument_Sans/static"
OUT_PATH = "assets/generated/instrument_font.h"

# (enum name, ttf file, pixel size)
FACES = [
    ("IFONT_SMALL",     "InstrumentSans-Regular.ttf",  13),
    ("IFONT_BODY",      "InstrumentSans-Regular.ttf",  15),
    ("IFONT_BODY_BOLD", "InstrumentSans-SemiBold.ttf", 15),
    ("IFONT_TITLE",     "InstrumentSans-Medium.ttf",   14),
    ("IFONT_H2",        "InstrumentSans-SemiBold.ttf", 21),
    ("IFONT_H1",        "InstrumentSans-SemiBold.ttf", 38),
]

FIRST, LAST = 32, 126


def main():
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        print("ERROR: Pillow is required (pip install Pillow)", file=sys.stderr)
        sys.exit(1)

    faces_out = []
    for enum_name, ttf, px in FACES:
        path = os.path.join(FONT_DIR, ttf)
        font = ImageFont.truetype(path, px)
        ascent, descent = font.getmetrics()

        # Tabular digits: widest digit advance wins
        digit_adv = max(int(round(font.getlength(d))) for d in "0123456789")

        glyphs = []   # (advance, bx, by, w, h, offset)
        blob = bytearray()
        for code in range(FIRST, LAST + 1):
            ch = chr(code)
            adv = digit_adv if ch.isdigit() else int(round(font.getlength(ch)))
            l, t, r, b = font.getbbox(ch)
            gw, gh = r - l, b - t
            if gw <= 0 or gh <= 0:
                glyphs.append((adv, 0, 0, 0, 0, 0))
                continue
            img = Image.new("L", (gw, gh), 0)
            draw = ImageDraw.Draw(img)
            draw.text((-l, -t), ch, font=font, fill=255)
            # Center digits inside the shared tabular advance
            bx = l
            if ch.isdigit():
                bx = l + (digit_adv - int(round(font.getlength(ch)))) // 2
            off = len(blob)
            blob += img.tobytes()
            glyphs.append((adv, bx, t, gw, gh, off))
        faces_out.append((enum_name, px, ascent, descent, glyphs, bytes(blob)))

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as f:
        f.write("/* Generated by tools/generate_system_font.py — do not edit. */\n")
        f.write("#ifndef INSTRUMENT_FONT_H\n#define INSTRUMENT_FONT_H\n")
        f.write("#include <stdint.h>\n\n")
        f.write("typedef struct {\n")
        f.write("    int16_t  adv;     /* pen advance, px           */\n")
        f.write("    int16_t  bx, by;  /* bitmap offset from pen/top */\n")
        f.write("    uint16_t w, h;    /* bitmap size                */\n")
        f.write("    uint32_t off;     /* offset into face bitmap    */\n")
        f.write("} ifont_glyph_t;\n\n")
        f.write("typedef struct {\n")
        f.write("    const ifont_glyph_t* glyphs;  /* ASCII 32..126 */\n")
        f.write("    const uint8_t*       bitmap;\n")
        f.write("    uint8_t size, ascent, descent, line_h;\n")
        f.write("} ifont_face_t;\n\n")
        f.write(f"#define IFONT_FIRST {FIRST}\n#define IFONT_LAST {LAST}\n\n")

        for i, (name, px, asc, desc, glyphs, blob) in enumerate(FACES_iter(faces_out)):
            f.write(f"/* face {i}: {name} ({px}px, ascent {asc}, descent {desc}) */\n")
            f.write(f"static const ifont_glyph_t g_if{i}_glyphs[{LAST-FIRST+1}] = {{\n")
            for g in glyphs:
                f.write("    {%d,%d,%d,%d,%d,%du},\n" % g)
            f.write("};\n")
            f.write(f"static const uint8_t g_if{i}_bitmap[{max(1,len(blob))}] = {{\n")
            for o in range(0, len(blob), 24):
                f.write("    " + ",".join(str(v) for v in blob[o:o+24]) + ",\n")
            if not blob:
                f.write("    0,\n")
            f.write("};\n\n")

        names = ", ".join(n for n, _, _ in FACES)
        f.write("enum { %s, IFONT_COUNT };\n\n" % names)
        f.write("static const ifont_face_t g_ifonts[IFONT_COUNT] = {\n")
        for i, (name, px, asc, desc, glyphs, blob) in enumerate(faces_out):
            f.write("    { g_if%d_glyphs, g_if%d_bitmap, %d, %d, %d, %d },\n"
                    % (i, i, px, asc, desc, asc + desc))
        f.write("};\n\n#endif /* INSTRUMENT_FONT_H */\n")

    total = sum(len(b) for _, _, _, _, _, b in faces_out)
    print(f"Generated {OUT_PATH} ({total} bytes of glyph coverage)")


def FACES_iter(faces_out):
    for name, px, asc, desc, glyphs, blob in faces_out:
        yield (name, px, asc, desc, glyphs, blob)


if __name__ == "__main__":
    main()
